name: trungchuyen
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.17+22

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_bloc: ^4.0.0
  get: 4.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^4.0.1
  equatable: ^1.2.0
  dotted_border: ^1.0.5
  google_fonts: ^1.1.0
  material_design_icons_flutter: ^4.0.5345
  shared_preferences: ^2.0.0
  font_awesome_flutter: ^9.0.0
  cached_network_image: ^2.1.0+1
  animator: ^1.0.0+3
  connectivity: ^3.0.3
  logger: ^1.0.0
  fluttertoast: ^8.0.3
  country_pickers: ^2.0.0
  flutter_ringtone_player: ^3.0.0
  flutter_page_indicator: ^0.0.3
  dio: ^3.0.10
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  intl: any
  overlay_support: ^1.2.0
  google_maps_flutter: ^1.1.1
  google_maps_controller: ^1.1.0
  flutter_animarker: ^1.0.0
  async: ^2.4.2
  flutter_polyline_points: ^0.2.4
  maps_toolkit: ^1.1.0+2
  location: ^3.0.0
  geocoder: ^0.2.1
  interactive_maps_marker: ^0.0.2
  flutter_carousel_slider: ^1.0.8
  table_calendar: ^2.2.3
  flutter_slidable: ^0.5.7
  image_picker: ^0.6.6+5
  socket_io_client: ^0.9.11
  liquid_pull_to_refresh: ^2.0.0
  pin_code_text_field: ^1.8.0
  #  flutter_datetime_picker: ^1.5.0
  syncfusion_flutter_datepicker: ^18.4.30-beta
#  firebase_auth: ^0.18.1
  #8.0.0-dev.12
#  firebase_core : ^0.7.0
  firebase_messaging: ^8.0.0-dev.12
  firebase_analytics: any
  url_launcher: any
  snapping_sheet: ^3.0.0+2
  flutter_spinkit: ^4.1.2
  countdown_progress_indicator: ^0.1.0
  circular_countdown_timer: ^0.2.0
  wakelock: ^0.5.1
  new_version: any
  adaptive_dialog: ^0.9.4
  timelines: ^0.1.0
  open_appstore: ^1.0.2
  in_app_update: ^2.0.0
#  cloud_firestore: ^0.16.0+1
  jiffy: any
  rxdart: any
  timezone: ^0.6.1



dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/locales/vi.json
    - assets/locales/en.json
    - assets/data.json

