name: trungchuyen
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.21+28

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  open_store: ^0.3.1
  dio: ^4.0.1
#  google_fonts: ^2.3.2
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.0.0
  shared_preferences: ^2.0.7
  material_design_icons_flutter: ^5.0.6595
  equatable: ^2.0.3
  dotted_border: ^2.0.0+2
#  flutter_local_notifications: ^9.2.0
  logger: ^1.1.0
  overlay_support: ^2.0.1
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.4.0
  cloud_firestore: ^4.5.0
  omni_datetime_picker: any
#  firebase_core_platform_interface: 4.4.0
#  image_picker: ^0.8.5+3
#  animator: ^1.0.0+3
  connectivity: ^3.0.3
  oktoast: ^3.1.3

  fluttertoast: any
#  country_pickers: ^2.0.0
#  flutter_ringtone_player: ^3.0.0
#  flutter_page_indicator: ^0.0.3

#  freezed: ^0.12.7
#  freezed_annotation: ^0.12.0
  intl: ^0.18.1
#  overlay_support: ^1.2.0
#  google_maps_flutter: ^1.1.1
#  google_maps_controller: ^1.1.0
#  flutter_animarker: ^1.0.0
#  async: ^2.4.2
#  flutter_polyline_points: ^0.2.4
#  maps_toolkit: ^1.1.0+2
#  location: any
#  geolocator: ^8.2.1
#  geocoder: any
#  interactive_maps_marker: ^0.0.2
#  flutter_carousel_slider: any
  table_calendar:
#  flutter_slidable: ^0.5.7
  flutter_slidable: ^1.3.0
  socket_io_client: ^2.0.1
#  image_picker: ^0.8.5+3
#  liquid_pull_to_refresh: ^2.0.0
#  pin_code_text_field: ^1.8.0
  get: ^4.5.1
#  date_time_picker: any
  flutter_local_notifications: any
#  syncfusion_flutter_datepicker: ^18.4.30-beta
#  firebase_auth: ^0.18.1
  #8.0.0-dev.12
#  firebase_core : ^0.7.0
#  firebase_messaging: ^8.0.0-dev.12
#  firebase_analytics: any
#  url_launcher: any
#  snapping_sheet: ^3.0.0+2
  flutter_spinkit: ^5.1.0
#  countdown_progress_indicator: ^0.1.0
#  circular_countdown_timer: ^0.2.0
#  wakelock: ^0.5.1
  new_version: any
#  adaptive_dialog: ^0.9.4
  adaptive_dialog: ^1.6.3
  timelines: ^0.1.0
#  open_appstore: ^1.0.2
#  in_app_update: ^2.0.0
#  cloud_firestore: ^0.16.0+1
  jiffy: ^5.0.0
#  rxdart: any
#  timezone: any
  persistent_bottom_nav_bar: ^4.0.2



dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/locales/vi.json
    - assets/locales/en.json
    - assets/data.json

